export const quotes = [
	'The universe is a dark forest. Every civilization is an armed hunter stalking through the trees like a ghost.',
	'In the universe, there are countless civilizations, but the universe is also a dark forest. A hunter who sees another hunter must shoot, or be shot.',
	'The universe is not a fairy tale. It is not a place where good always triumphs over evil.',
	'The most important thing is not to be afraid. Fear is the mind-killer.',
	'We are all made of star-stuff.',
	'The universe is not only stranger than we imagine, it is stranger than we can imagine.',
	'In the beginning, there was nothing, which exploded.',
	'The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself.',
	'Two possibilities exist: either we are alone in the universe or we are not. Both are equally terrifying.',
	"The universe is a pretty big place. If it's just us, seems like an awful waste of space.",
	"Space is big. Really big. You just won't believe how vastly, hugely, mind-bogglingly big it is.",
	'The universe is under no obligation to make sense to you.',
	'We are the universe experiencing itself.',
	'The universe is not required to be in perfect harmony with human ambition.',
	'In the vastness of space and the immensity of time, it is my joy to share a planet and an epoch with you.',
	"The universe is a cruel, uncaring void. The key to being happy isn't a search for meaning. It's to just keep yourself busy with unimportant nonsense, and eventually you'll be dead.",
	'We are all connected; to each other, biologically. To the earth, chemically. To the rest of the universe, atomically.',
	'The universe is not only queerer than we suppose, but queerer than we can suppose.',
	'The cosmos is all that is or ever was or ever will be.',
	'Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist.',
	'The universe is a grand book which cannot be read until one first learns to comprehend the language and become familiar with the characters in which it is composed.',
	'The universe is full of magical things patiently waiting for our wits to grow sharper.',
	'The universe is not hostile, nor yet is it friendly. It is simply indifferent.',
	'We are stardust, we are golden, we are billion year old carbon.',
	'The universe is expanding. The scope of this statement is not always fully appreciated.',
	'The universe is a machine that has no purpose. That is why it is perfect.',
	'In the universe, there are things that are known, and things that are unknown, and in between, there are doors.',
	'The universe is not only stranger than we imagine, it is stranger than we can imagine.',
	'We are the cosmos made conscious and life is the means by which the universe understands itself.',
	"The universe is a pretty big place. If it's just us, seems like an awful waste of space.",
	"Time is the one thing that can't be stopped. Like a sharp blade, it silently cuts through hard and soft, constantly advancing. Nothing is capable of jolting it even the slightest bit, but it changes everything.",
	"Make time for civilization, for civilization won't make time.",
	'Life needed smoothness, but it also needed direction. One could not always be returning to the point of origin.',
	"Of course she's not afraid. She knows that the sun will rise again tomorrow.",
	'I have a dream that one day brilliant sunlight will illuminate the dark forest.',
	"But in this dark forest, there's a stupid child named humanity, who has built a bonfire and is standing beside it shouting, 'Here I am! Here I am!'",
	"There's nothing excessive about imagination. Especially where love is concerned.",
	'Darkness was the mother of life and of civilization',
];

export const getRandomQuote = () => {
	return quotes[Math.floor(Math.random() * quotes.length)];
};
